name: bandit
version: "1.0.1"
summary: Security Scanner for Python.
description:
    Static Code Analysis for Python code.
base: core18
confinement: classic
parts:
  bandit:
    plugin: python
    source-tag: "1.6.2"
    source: https://github.com/PyCQA/bandit.git
apps:
  bandit:
    command: bandit
    plugs:
    - network